scripts:
  - name: Set up local.properties
    script: |
      echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties
  - name: Get Flutter packages
    script: |
      flutter pub get
  - name: Build Android APK
    script: |
      flutter pub get
      flutter build apk --release --android-skip-build-dependency-validation
